services:
  tracker:
    build: .
    image: tracker:latest
    restart: unless-stopped
    environment:
      - BT_HTTP_ADDRESS=
      - BT_HTTP_PORT=8080
      - BT_UDP_ADDRESS=
      - BT_UDP_PORT=6881
      - BT_UDP_URL=udp://localhost:6881
    ports:
      - "8080:8080/tcp"
      - "6881:6881/udp"
