// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Peer struct {
	InfoHash   string
	PeerID     string
	Downloaded int64
	Left       int64
	Uploaded   int64
	Event      int64
	Ip         int64
	Port       int64
	Key        int64
	UpdatedAt  time.Time
}

type Torrent struct {
	InfoHash  string
	Magnet    string
	Completed int64
}
