// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: peers.sql

package db

import (
	"context"
	"time"
)

const deleteExpiredPeers = `-- name: DeleteExpiredPeers :execrows
DELETE FROM peers
WHERE updated_at < ?
`

func (q *Queries) DeleteExpiredPeers(ctx context.Context, updatedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredPeers, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPeer = `-- name: GetPeer :one
SELECT info_hash, peer_id, downloaded, "left", uploaded, event, ip, port, "key", updated_at FROM peers
WHERE info_hash = ? AND peer_id = ?
LIMIT 1
`

type GetPeerParams struct {
	InfoHash string
	PeerID   string
}

func (q *Queries) GetPeer(ctx context.Context, arg GetPeerParams) (Peer, error) {
	row := q.db.QueryRowContext(ctx, getPeer, arg.InfoHash, arg.PeerID)
	var i Peer
	err := row.Scan(
		&i.InfoHash,
		&i.PeerID,
		&i.Downloaded,
		&i.Left,
		&i.Uploaded,
		&i.Event,
		&i.Ip,
		&i.Port,
		&i.Key,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPeers = `-- name: ListAllPeers :many
SELECT info_hash, peer_id, downloaded, "left", uploaded, event, ip, port, "key", updated_at FROM peers
`

func (q *Queries) ListAllPeers(ctx context.Context) ([]Peer, error) {
	rows, err := q.db.QueryContext(ctx, listAllPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Peer
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.InfoHash,
			&i.PeerID,
			&i.Downloaded,
			&i.Left,
			&i.Uploaded,
			&i.Event,
			&i.Ip,
			&i.Port,
			&i.Key,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeersByTorrent = `-- name: ListPeersByTorrent :many
SELECT info_hash, peer_id, downloaded, "left", uploaded, event, ip, port, "key", updated_at FROM peers
WHERE info_hash = ?
`

func (q *Queries) ListPeersByTorrent(ctx context.Context, infoHash string) ([]Peer, error) {
	rows, err := q.db.QueryContext(ctx, listPeersByTorrent, infoHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Peer
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.InfoHash,
			&i.PeerID,
			&i.Downloaded,
			&i.Left,
			&i.Uploaded,
			&i.Event,
			&i.Ip,
			&i.Port,
			&i.Key,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPeer = `-- name: UpsertPeer :exec
INSERT INTO peers (
  info_hash, peer_id, downloaded, "left", uploaded, event, ip, port, "key", updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (info_hash, peer_id) DO UPDATE SET
  downloaded = excluded.downloaded,
  "left" = excluded."left",
  uploaded = excluded.uploaded,
  event = excluded.event,
  ip = excluded.ip,
  port = excluded.port,
  "key" = excluded."key",
  updated_at = excluded.updated_at
`

type UpsertPeerParams struct {
	InfoHash   string
	PeerID     string
	Downloaded int64
	Left       int64
	Uploaded   int64
	Event      int64
	Ip         int64
	Port       int64
	Key        int64
	UpdatedAt  time.Time
}

func (q *Queries) UpsertPeer(ctx context.Context, arg UpsertPeerParams) error {
	_, err := q.db.ExecContext(ctx, upsertPeer,
		arg.InfoHash,
		arg.PeerID,
		arg.Downloaded,
		arg.Left,
		arg.Uploaded,
		arg.Event,
		arg.Ip,
		arg.Port,
		arg.Key,
		arg.UpdatedAt,
	)
	return err
}
