// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: torrents.sql

package db

import (
	"context"
)

const getTorrent = `-- name: GetTorrent :one
SELECT info_hash, magnet, completed FROM torrents
WHERE info_hash = ?
LIMIT 1
`

func (q *Queries) GetTorrent(ctx context.Context, infoHash string) (Torrent, error) {
	row := q.db.QueryRowContext(ctx, getTorrent, infoHash)
	var i Torrent
	err := row.Scan(&i.InfoHash, &i.Magnet, &i.Completed)
	return i, err
}

const incrementCompleted = `-- name: IncrementCompleted :exec
UPDATE torrents
SET completed = completed + 1
WHERE info_hash = ?
`

func (q *Queries) IncrementCompleted(ctx context.Context, infoHash string) error {
	_, err := q.db.ExecContext(ctx, incrementCompleted, infoHash)
	return err
}

const listTorrents = `-- name: ListTorrents :many
SELECT info_hash, magnet, completed FROM torrents
ORDER BY info_hash
`

func (q *Queries) ListTorrents(ctx context.Context) ([]Torrent, error) {
	rows, err := q.db.QueryContext(ctx, listTorrents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Torrent
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(&i.InfoHash, &i.Magnet, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerTorrent = `-- name: RegisterTorrent :one
INSERT INTO torrents (info_hash, magnet, completed)
VALUES (?, ?, ?)
ON CONFLICT (info_hash) DO UPDATE SET info_hash = excluded.info_hash
RETURNING info_hash, magnet, completed
`

type RegisterTorrentParams struct {
	InfoHash  string
	Magnet    string
	Completed int64
}

func (q *Queries) RegisterTorrent(ctx context.Context, arg RegisterTorrentParams) (Torrent, error) {
	row := q.db.QueryRowContext(ctx, registerTorrent, arg.InfoHash, arg.Magnet, arg.Completed)
	var i Torrent
	err := row.Scan(&i.InfoHash, &i.Magnet, &i.Completed)
	return i, err
}
